app1/urls.py
from django.urls import path
from . import views

app_name = 'app1'

urlpatterns = [

    path('calc/', views.calc, name="calc"),
    path('help/', views.help, name="help"),
    path('sp/', views.sp, name="sp"),
    path('registros/', views.registros, name="registros"),
    path('form/', views.form_name, name="form"),
    path('modelform/', views.users, name="modelform"),

]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views
from django.conf import settings

urlpatterns = [

    path('', views.index, name="index"),
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls, name='admin'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

app1/models.py
from django.db import models


# Create your models here.


class Topico(models.Model):
    nome = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.nome


class Webpage(models.Model):
    topico = models.ForeignKey(Topico, on_delete=models.CASCADE)
    nome = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.nome


class RegistroAcesso(models.Model):
    pagina = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    data = models.DateField()

    def __str__(self):
        return str(self.data)


class DadosForm(models.Model):
    nome = models.CharField(max_length=264, unique=True)
    sobrenome = models.CharField(max_length=264, unique=True)
    email = models.EmailField(max_length=264, unique=True)
    endereco = models.CharField(max_length=264, unique=True)
    pais = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.nome


class Filme(models.Model):
    titulo = models.CharField(max_length=256)
    duracao = models.PositiveIntegerField()
    ano_lancamento = models.PositiveIntegerField()

    def __str__(self):
        return self.titulo


class Cliente(models.Model):
    nome = models.CharField(max_length=256)
    sobrenome = models.CharField(max_length=256)
    telefone = models.PositiveIntegerField()

    def __str__(self):
        return self.nome

app1/forms.py
from django import forms

from app1.models import DadosForm


class FormName(forms.Form):
    nome = forms.CharField()
    email = forms.EmailField()
    texto = forms.CharField(widget=forms.Textarea, max_length=100)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput)

    def clean_botcatcher(self):
      botcatcher = self.cleaned_data['botcatcher']
      if len(botcatcher) > 0:
          raise forms.ValidationError("GOTCHA BOT!")
      return botcatcher


class ModelForm(forms.ModelForm):
    class Meta:
        model = DadosForm
        fields = "__all__"

app1/views.py
# def index(request):
#    return HttpResponse("Hello World!")
from django.shortcuts import render
from app1.models import RegistroAcesso
from .forms import FormName, ModelForm


def index(request):
    return render(request, 'app1/index.html')

def calc(request):
    return render(request, 'app1/calc.html')

def help(request):
    return render(request, 'app1/help.html')

def sp(request):
    return render(request, 'app1/sp.html')

def registros(request):
    lista_paginas = RegistroAcesso.objects.order_by('data')
    dict_lista2 = {"lista_acessos": lista_paginas}
    return render(request, 'app1/registros.html', dict_lista2)

def form_name(request):
    form = FormName()

    if request.method == 'POST':
        form = FormName(request.POST)

        if form.is_valid():
           print("Os campos estão corretos")
           print("Nome: " + form.cleaned_data['nome'])
           print("Email: " + form.cleaned_data['email'])
           print("Texto: " + form.cleaned_data['texto'])

    return render(request, 'app1/form.html', {"form": form})


def users(request):
    form = ModelForm()

    if request.method == "POST":
        form = ModelForm(request.POST)
        if form.is_valid():
            print("cadastrado: " + form.cleaned_data['nome'])
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')

    return render(request, 'app1/modelform.html', {'form': form})

app1/templates/app1/calc.html
<!DOCTYPE html>
{% extends "app1/index.html" %}
{% load static %}

 <html lang="pt-BR">


   {% block rodape %}
     <body>

        <head>
           <title>Calculadora</title>
           <link rel="stylesheet" type="text/css" href="{% static "css/calculadora.css" %}">
           <script src="{% static "js/calculo.js" %}"></script>
        </head>

       <div class="conteiner">


              <p id="visor">0</p>           

              <div class="teclado">

                   <table style="width: 100%">
                      <tr>

                          <td><button class='button' onclick="btlimpar()">C</button></td>
                          <td><button class='button' onclick="btponto()">.</button></td>
                          <td><button class='button' id="divisao" onclick="operador(this.id)">/</button></td>

                      </tr>

                      <tr>
                            <td> <button class='button' id="soma" onclick="operador(this.id)" >+</th></button></td>
                            <td> <button class='button' id="subtracao" onclick="operador(this.id)" >-</button></td>
                            <td> <button class='button' id="multiplicacao" onclick="operador(this.id)" >x</button></td>

                      </tr>

                      <tr>
                            <td> <button class='button' id="b7" onclick="botnumero(this.id)" >7</button></td>
                            <td> <button class='button' id="b8" onclick="botnumero(this.id)" >8</button></td>
                            <td> <button class='button' id="b9" onclick="botnumero(this.id)" >9</button></td>

                      </tr>

                      <tr>
                            <td> <button class='button' id="b4" onclick="botnumero(this.id)" >4</button></td>
                            <td> <button class='button' id="b5" onclick="botnumero(this.id)" >5</button></td>
                            <td> <button class='button' id="b6" onclick="botnumero(this.id)" >6</button></td>

                      </tr>

                      <tr>

                           <td> <button class='button' id="b1" onclick="botnumero(this.id)" >1</button></td>
                           <td> <button class='button' id="b2" onclick="botnumero(this.id)" >2</button></td>
                           <td> <button class='button' id="b3" onclick="botnumero(this.id)" >3</button></td>
  
                      </tr>

                      <tr>

                          <td><button class='button' onclick="maisEmenos()">+/-</button></td>
                          <td> <button class='button' id="b0" onclick="botnumero(this.id)" >0</button></td>
                          <td><button class='button' onclick="resultado()">=</button></td>

                      </tr>
                   </table>

              </div>
             <div class="imagem"></div>
       </div>


     </body>
   {% endblock %}
 </html>

app1/templates/app1/form.html
<!DOCTYPE html>
{% extends "app1/index.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load static %}

  <html lang="pt-BR">

     {% block rodape %}

         <body>
             <div class="container">
                          <head>
                                <meta charset="UTF-8">
                                <title>Formulário</title>
                                 <link rel="stylesheet" type="text/css" href="{% static "css/form.css" %}"/>
                          </head>

                       <h1> Vamos Preencher o Form </h1>

                    <form method="POST" class="grupo" >

                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" class="btn btn-primary" value="Submit">
                    </form>
             </div>
         </body>

     {% endblock %}

  </html>

app1/templates/app1/help.html
<!DOCTYPE html>
{% extends "app1/index.html" %}
{% load static %}

  <html lang="pt-BR">
    <head>
          <meta charset="UTF-8">
          <title>Ajuda</title>
    </head>
    <body>

            {% block imagem-fundo %}

                <h1>Área de Ajuda!
                </h1>


            {% endblock %}

    </body>
  </html>

app1/templates/app1/index.html
<!DOCTYPE html>
{% load static %}

  <html lang="pt-BR">
    <head>
       <meta charset="UTF-8">
       <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <title>Home</title>
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
       <link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}"/>
    </head>
      <body>
        {% block body %}
          <div class="toda_pagina">
            {% block toda-pagina %}
            {% endblock %}
              <div class="menu">
                     <nav>
                       <a href="{% url 'index' %}">Home</a>
                       <a href="{% url 'app1:form' %}">Form</a>
                       <a href="{% url 'app1:modelform' %}">Model Form</a>
                       <a href="{% url 'app1:sp' %}">São Paulo</a>
                       <a href="{% url 'app1:calc' %}">Calculadora</a>
                       <a href="{% url 'app1:registros' %}">Registros de Acesso</a>
                       <a href="{% url 'admin:index' %}">Django Admin</a>
                       <a href="{% url 'app1:help' %}">Ajuda</a>
                     </nav>
                  {% block menu %}
                  {% endblock %}
              </div>
               {% block conteudo %}

                       <div class="conteudo">
                          {% block rodape %}
                             <div class="imagem-fundo">
                              {% block imagem-fundo %}
                              {% endblock %}
                             </div>
                          {% endblock %}
                       </div>

                   <footer class="footer mt-auto text-center fixed-bottom">
                        <div class="rodape">
                            <a>Desenvolvida por Isabella Fraga &copy; Copyright</a>
                        </div>
                   </footer>

               {% endblock %}
                           <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
                           <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
                           <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

          </div>
        {% endblock %}
      </body>
  </html>

app1/templates/app1/modelform.html
<!DOCTYPE html>
{% extends "app1/index.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load static %}

  <html lang="pt-BR">

      {% block rodape %}

            <body>

                  <div class="container">


                          <head>
                                <meta charset="UTF-8">
                                <title>Formulário</title>
                                 <link rel="stylesheet" type="text/css" href="{% static "css/modelform.css" %}"/>
                          </head>

                                        <h1> Vamos Preencher o Model Form </h1>

                                        <form method="POST" class="grupo" action="">
                                             {% csrf_token %}
                                             {{ form|crispy }}
                                        </form>
                  </div>
            </body>
      {% endblock %}
  </html>

app1/templates/app1/registros.html
<!DOCTYPE html>

{% extends "app1/index.html" %}
{% load static %}


  <html lang="pt-BR">


    {% block rodape %}
       <body>
               <head>
                     <meta charset="UTF-8">
                     <title>Registros de Acesso</title>
                     <link rel="stylesheet" type="text/css" href="{% static "css/registros.css" %}"/>
               </head>
                    <h2>Aqui estão os Registros de Acesso:</h2>
          <div class="djangtwo">
                {% if lista_acessos %}
                   <table>
                      <thead>
                             <th>Nome da Página</th>
                             <th>Data de Acesso</th>
                      </thead>

                       {% for acesso in lista_acessos %}

                             <tr>
                                  <td>{{ acesso.pagina|upper }}</td>
                                  <td>{{ acesso.data|date:"d F Y" }}</td>
                             </tr>
                       {% endfor %}
                   </table>

                {% else %}
                         <p>Sem Registros. Tabela Não Criada.</p>
                {% endif %}
          </div>

       </body>
    {% endblock %}
  </html>

app1/templates/app1/sp.html
<!DOCTYPE HTML>
{% extends "app1/index.html" %}
{% load static %}

 <html lang="pt-BR">


   {% block conteudo %}



     <body>
              <head>
                        <TITLE>São Paulo</TITLE>
                        <link rel="stylesheet" type="text/css" href="{% static "css/saopaulo.css" %}">
              </head>

       <div class="conteiner">

           <h1> <a href= "{% url 'app1:sp' %}">O que eu mais gosto em São Paulo</a> </h1>
           <div class="Lugares">
                 <h2>Passear na Avenida Paulista</h2>
                 <img src="https://media-cdn.tripadvisor.com/media/photo-s/18/99/d8/ed/paulista.jpg" alt="Avenida Paulista">
                 <p>
                      Um dos principais centros financeiros da cidade, a avenida Paulista
                      também possui diversas opções de entretenimento. Endereço do Museu
                      de Arte de São Paulo, <i>MASP</i>, do Teatro Gazeta e muitos outros,
                      a região é de fácil acesso graças as diversas linhas de ônibus que
                      cruzam a avenida e a linha de metrô que passa por baixo dela.
                 </p> 
                  <p>
                     A avenida paulista sempre é assunto. O que será que estão falando a respeito
                     no <a href="https://twitter.com/search?q=Avenida Paulista">Twitter</a>.
                  </p>
           </div>


           <div class="Lugares">
                  <h2>Os Bares da Vila Madalena</h2>
                  <img src="https://www.guiadasemana.com.br/contentFiles/image/opt_w840h0/2019juliana/lugares/vila-madalena/28060886-1719018988119237-4294555165498106193-o.jpg" alt="Bares da Vila Madalena">
                  <p>
                     Depois de um dia de trabalho, nada melhor do que um bom chopp, um
                     petisco e uma conversa em uma mesa de bar. Opções de sobra na região
                     das ruas Aspicuelta, Fradique Coutinho e Wisard.
                  </p>
                  <p>
                     Veja quais os melhores bares e restaurantes da região no
                      <a href="https://vejasp.abril.com.br/cidades/melhor-da-vila-madalena-restaurantes/">Guia da VEJA São Paulo</a>.
                  </p>
           </div>

          
             <div class="Lugares">
                 <h2>O Parque de Ibirapuera</h2>
                 <img src="http://www.saopauloinfoco.com.br/wp-content/uploads/2013/03/Parque-do-Ibirapuera_Cidade-de-S%C3%A3o-Paulo.jpg" alt="O Parque de Ibirapuera">
                 <p>
                      Um dos cartões postais da cidade, o parque dispõe de mais de 1,5 km²
                      de área verde, lagos artificiais e pistas de cooper e ciclismo. E se
                      isso não fosse o suficiente, o parque costuma ser palco de diversos
                      eventos culturais ao longo do ano.
                    
                 </p>
                 <p>
                       Veja no <a href="http://goo.gl/maps/HoH8">mapa</a> como chegar ao parque.
                 </p>
             </div>
       </div>

       <div class="Menu">
                <h4>E existem muitos outros lugares interessantes na cidade...</h4>
                
                   <ol>
                      <li>Mercado Municipal.</li> 
                      <li>A Sala São Paulo.</li>
                      <li>Os estádios dos principais times de futebol da cidade.</li> 
                      <li>Diversos museus, como o Memorial da América Latina da Língua Portuguesa e o Museu do Ipiranga.</li> 
                      <li>E mais!</li> 
                   </ol>
       </div>
         <div class="rodape1">
             <p>
                 Parte do livro "HMTL5 e CSS3: Domine a web do futuro"
             </p>
         </div>
                       <div class="rodape">
                           <p>Página HTML desenvolvida por Isabella Fraga ©</p>
                       </div>

     </body>
   {% endblock %}
 </html>